### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ghost**
Bumping version after locking down dependencies

### CODE REVIEW

**Comment by philcockfield** [comment]
Cool.

**Comment by ghost** [comment]
Hey @philcockfield , I'm trying to publish this version so givenwhenthen can consume it with locked down deps. Can you add me as an admin for this module on npm (or publish for me)?

**Comment by philcockfield** [comment]
OK, so what you've got on _master_ now is ready to be published?

On Sun, Dec 2, 2012 at 1:33 PM, Robert Quinlivan
notifications@github.comwrote:

> Hey @philcockfield https://github.com/philcockfield , I'm trying to
> publish this version so givenwhenthen can consume it with locked down deps.
> Can you add me as an admin for this module on npm (or publish for me)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/philcockfield/open.core/pull/27#issuecomment-10924234.

## 

*Phil *Cockfield

**Comment by ghost** [comment]
Yep, should be

**Comment by philcockfield** [comment]
Done!

https://npmjs.org/package/open.core

**Pull request merged**
